[tox]
envlist = copying,{py310,py313,py314}-{lint,tests},cli
skip_missing_interpreters = True

[testenv]
allowlist_externals =
    cli:        {[testenv:cli]allowlist_externals}
    copying:    {[testenv:copying]allowlist_externals}
deps=
    -rtests_utils/test-requirements.txt
commands=
    tests:   {[testenv:tests]commands}
    lint:    {[testenv:lint]commands}
    cli:     {[testenv:cli]commands}
    copying: {[testenv:copying]commands}

[testenv:tests]
commands=
    pytest {posargs}

[testenv:lint]
commands=
    ruff format --check iotlabwscli
    ruff check iotlabwscli
    isort --check-only iotlabwscli
    pylint --rcfile=pyproject.toml iotlabwscli

[testenv:copying]
allowlist_externals=
    /bin/bash
    /usr/bin/bash
commands=
    bash tests_utils/check_license.sh

[testenv:cli]
allowlist_externals=
    /bin/bash
    /usr/bin/bash
commands=
    bash -exc "iotlab-ws --help > /dev/null"
